apiVersion: apps/v1
kind: Deployment
metadata:
  name: bussines-frontend
  labels:
    app: bussines-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bussines-frontend
  template:
    metadata:
      labels:
        app: bussines-frontend
    spec:
      containers:
      - name: bussines-frontend
        image: bussines-frontend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "0.3"
            memory: "256Mi"
          requests:
            cpu: "0.1"
            memory: "128Mi"
        env:
          - name: BACKEND_HOST
            value: "bussines-backend-service"
---
apiVersion: v1
kind: Service
metadata:
  name: bussines-frontend-service
spec:
  selector:
    app: bussines-frontend
  ports:
  - port: 80
    targetPort: 80
  type: NodePort